initial commit

diff --git a/ROMFS/px4fmu_common/init.d/rcS b/ROMFS/px4fmu_common/init.d/rcS
--- a/ROMFS/px4fmu_common/init.d/rcS
+++ b/ROMFS/px4fmu_common/init.d/rcS
@@ -21,26 +21,35 @@ set +e
 # it wastes flash
 #
 set R /
+set AUTOCNF no
 set FCONFIG /fs/microsd/etc/config.txt
 set FEXTRAS /fs/microsd/etc/extras.txt
 set FRC /fs/microsd/etc/rc.txt
 set IOFW "/etc/extras/px4_io-v2_default.bin"
+set IO_PRESENT no
 set LOGGER_ARGS ""
 set LOGGER_BUF 8
+set MIXER none
+set MIXER_AUX none
+set MIXER_FILE none
+set MIXER_EXTRA none
+set OUTPUT_MODE none
 set PARAM_FILE ""
-set PARAM_BACKUP_FILE ""
+set PWM_OUT none
+set PWM_MAIN_RATE p:PWM_MAIN_RATE
+set PWM_AUX_OUT none
+set PWM_AUX_RATE p:PWM_AUX_RATE
+set PWM_EXTRA_OUT none
+set PWM_EXTRA_RATE p:PWM_EXTRA_RATE
+set EXTRA_MIXER_MODE none
 set RC_INPUT_ARGS ""
-set STORAGE_AVAILABLE no
+set SDCARD_AVAILABLE no
 set SDCARD_EXT_PATH /fs/microsd/ext_autostart
 set SDCARD_FORMAT no
+set SDCARD_MIXERS_PATH /fs/microsd/etc/mixers
 set STARTUP_TUNE 1
+set USE_IO no
 set VEHICLE_TYPE none
-
-# Airframe parameter versioning
-# Value set to 1 by default but can optionally be overridden in the airframe configuration startup script.
-# Airframe maintainers can ensure a reset to the airframe defaults during an update by increasing by one.
-# e.g. add line "set PARAM_DEFAULTS_VER 2" in your airframe file to build the first update that enforces a reset.
-set PARAM_DEFAULTS_VER 1
 
 #
 # Print full system version.
@@ -62,11 +71,11 @@ then
 			umount /fs/microsd
 
 		else
-			set STORAGE_AVAILABLE yes
+			set SDCARD_AVAILABLE yes
 		fi
 	fi
 
-	if [ $STORAGE_AVAILABLE = no -o $SDCARD_FORMAT = yes ]
+	if [ $SDCARD_AVAILABLE = no -o $SDCARD_FORMAT = yes ]
 	then
 		echo "INFO [init] formatting /dev/mmcsd0"
 		set STARTUP_TUNE 15 # tune 15 = SD_ERROR (overridden to SD_INIT if format + mount succeeds)
@@ -77,7 +86,7 @@ then
 
 			if mount -t vfat /dev/mmcsd0 /fs/microsd
 			then
-				set STORAGE_AVAILABLE yes
+				set SDCARD_AVAILABLE yes
 				set STARTUP_TUNE 14 # tune 14 = SD_INIT
 			else
 				echo "ERROR [init] card mount failed"
@@ -86,35 +95,20 @@ then
 			echo "ERROR [init] format failed"
 		fi
 	fi
-else
-	# Is there a device mounted for storage
-	if mft query -q -k MTD -s MTD_PARAMETERS -v /mnt/microsd
-	then
-		set STORAGE_AVAILABLE yes
-	fi
-fi
 
-if [ $STORAGE_AVAILABLE = yes ]
-then
-	if hardfault_log check
+	if [ $SDCARD_AVAILABLE = yes ]
 	then
-		set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
-		if hardfault_log commit
+		if hardfault_log check
 		then
-			hardfault_log reset
+			set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
+			if hardfault_log commit
+			then
+				hardfault_log reset
+			fi
 		fi
 	fi
 
-	# Check for an update of the ext_autostart folder, and replace the old one with it
-	if [ -e /fs/microsd/ext_autostart_new ]
-	then
-		echo "Updating external autostart files"
-		rm -r $SDCARD_EXT_PATH
-		mv /fs/microsd/ext_autostart_new $SDCARD_EXT_PATH
-	fi
-
 	set PARAM_FILE /fs/microsd/params
-	set PARAM_BACKUP_FILE "/fs/microsd/parameters_backup.bson"
 fi
 
 #
@@ -126,14 +120,13 @@ then
 	. $FRC
 else
 
-	# Load param file location from kconfig
-	. ${R}etc/init.d/rc.filepaths
-
-	# Check if /fs/mtd_params is a valid BSON file
-	if ! bsondump docsize /fs/mtd_caldata
+	#
+	# Set the parameter file the board supports params on
+	# MTD device.
+	#
+	if mft query -q -k MTD -s MTD_PARAMETERS -v /fs/mtd_params
 	then
-		echo "New /fs/mtd_caldata size is:"
-		bsondump docsize /fs/mtd_caldata
+		set PARAM_FILE /fs/mtd_params
 	fi
 
 	#
@@ -151,48 +144,46 @@ else
 		echo "ERROR [init] param import failed"
 		set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
 
-		bsondump $PARAM_FILE
+		param dump $PARAM_FILE
 
 		if [ -d "/fs/microsd" ]
 		then
-			# try to make a backup copy
-			cp $PARAM_FILE /fs/microsd/param_import_fail.bson
-
-			# try importing from backup file
-			if [ -f $PARAM_BACKUP_FILE ]
-			then
-				echo "[init] importing from parameter backup"
-
-				# dump current backup file contents for comparison
-				bsondump $PARAM_BACKUP_FILE
-
-				param import $PARAM_BACKUP_FILE
-
-				# overwrite invalid $PARAM_FILE with backup
-				cp $PARAM_BACKUP_FILE $PARAM_FILE
-			fi
-
-			param status
-
 			dmesg >> /fs/microsd/param_import_fail.txt &
+
+			# try to make a backup copy
+			cp $PARAM_FILE /fs/microsd/param_import_fail.bson &
+		fi
+
+		# try importing from backup file
+		if [ -f "/fs/microsd/parameters_backup.bson" ]
+		then
+			echo "[init] importing from parameter backup"
+
+			# dump current backup file contents for comparison
+			param dump /fs/microsd/parameters_backup.bson
+
+			param import /fs/microsd/parameters_backup.bson
 		fi
 	fi
 
-	if [ $STORAGE_AVAILABLE = yes ]
+	if [ $SDCARD_AVAILABLE = yes ]
 	then
-		param select-backup $PARAM_BACKUP_FILE
+		param select-backup /fs/microsd/parameters_backup.bson
 	fi
 
-	if mft query -q -k MFT -s MFT_ETHERNET -v 1
+	if ver hwcmp PX4_FMU_V5X PX4_FMU_V6X
 	then
 		netman update -i eth0
 	fi
 
-	# To trigger a parameter reset during boot SYS_AUTCONFIG was set to 1 before
+	#
+	# Set AUTOCNF flag to use it in AUTOSTART scripts.
+	#
 	if param greater SYS_AUTOCONFIG 0
 	then
-		# Reset parameters except airframe, parameter version, RC calibration, sensor calibration, flight modes, total flight time, flight UUID
-		param reset_all SYS_AUTOSTART SYS_PARAM_VER RC* CAL_* COM_FLTMODE* LND_FLIGHT* TC_* COM_FLIGHT*
+		# Wipe out params except RC*, flight modes, total flight time, calibration parameters, next flight UUID
+		param reset_all SYS_AUTO* RC* COM_FLTMODE* LND_FLIGHT* TC_* CAL_ACC* CAL_GYRO* COM_FLIGHT*
+		set AUTOCNF yes
 	fi
 
 	#
@@ -218,54 +209,6 @@ else
 	unset BOARD_RC_DEFAULTS
 
 	#
-	# Optional additional init file: rc.additional_init
-	#
-	set BOARD_RC_ADDITIONAL_INIT ${R}etc/init.d/rc.additional_init
-	if [ -f $BOARD_RC_ADDITIONAL_INIT ]
-	then
-		echo "Board additional init: ${BOARD_RC_ADDITIONAL_INIT}"
-		. $BOARD_RC_ADDITIONAL_INIT
-	fi
-	unset BOARD_RC_ADDITIONAL_INIT
-
-	# Load airframe configuration based on SYS_AUTOSTART parameter
-	if ! param compare SYS_AUTOSTART 0
-	then
-		# rc.autostart directly run the right airframe script which sets the VEHICLE_TYPE
-		# Look for airframe in ROMFS
-		. ${R}etc/init.d/rc.autostart
-
-		if [ ${VEHICLE_TYPE} = none ]
-		then
-			# Use external startup file
-			if [ $STORAGE_AVAILABLE = yes ]
-			then
-				. ${R}etc/init.d/rc.autostart_ext
-			else
-				echo "ERROR [init] SD card not mounted - can't load external airframe"
-			fi
-		fi
-
-		if [ ${VEHICLE_TYPE} = none ]
-		then
-			echo "ERROR [init] No airframe file found for SYS_AUTOSTART value"
-			param set SYS_AUTOSTART 0
-			tune_control play error
-		fi
-	fi
-
-	# Check parameter version and reset upon airframe configuration version mismatch.
-	# Reboot required because "param reset_all" would reset all "param set" lines from airframe.
-	if ! param compare SYS_PARAM_VER ${PARAM_DEFAULTS_VER}
-	then
-		echo "Switched to different parameter version. Resetting parameters."
-		param set SYS_PARAM_VER ${PARAM_DEFAULTS_VER}
-		param set SYS_AUTOCONFIG 1
-		param save
-		reboot
-	fi
-
-	#
 	# Start the tone_alarm driver.
 	# Needs to be started after the parameters are loaded (for CBRK_BUZZER).
 	#
@@ -275,7 +218,7 @@ else
 	# Waypoint storage.
 	# REBOOTWORK this needs to start in parallel.
 	#
-	if param compare -s SYS_DM_BACKEND 1
+	if param compare SYS_DM_BACKEND 1
 	then
 		dataman start -r
 	else
@@ -292,14 +235,6 @@ else
 	send_event start
 
 	#
-	# Start the hardfault streamer.
-	#
-	if param compare -s SYS_HF_MAV 1
-	then
-		hardfault_stream start
-	fi
-
-	#
 	# Start the resource load monitor.
 	#
 	load_mon start
@@ -309,8 +244,26 @@ else
 	#
 	rgbled start -X -q
 	rgbled_ncp5623c start -X -q
-	rgbled_lp5562 start -X -q
-	rgbled_is31fl3195 start -X -q
+
+	#
+	# Set parameters and env variables for selected AUTOSTART.
+	#
+	set AUTOSTART_PATH etc/init.d/rc.autostart
+	if ! param compare SYS_AUTOSTART 0
+	then
+		if param greater SYS_AUTOSTART 1000000
+		then
+			# Use external startup file
+			if [ $SDCARD_AVAILABLE = yes ]
+			then
+				set AUTOSTART_PATH etc/init.d/rc.autostart_ext
+			else
+				echo "ERROR [init] SD card not mounted - trying to load airframe from ROMFS"
+			fi
+		fi
+		. ${R}$AUTOSTART_PATH
+	fi
+	unset AUTOSTART_PATH
 
 	#
 	# Override parameters from user configuration file.
@@ -321,25 +274,111 @@ else
 		. $FCONFIG
 	fi
 
+	#
+	# If autoconfig parameter was set, reset it and save parameters.
+	#
+	if [ $AUTOCNF = yes ]
+	then
+		param set SYS_AUTOCONFIG 0
+	fi
+
+	#
+	# Check if UAVCAN is enabled, default to it for ESCs.
+	#
+	if param greater -s UAVCAN_ENABLE 0
+	then
+		# Start core UAVCAN module.
+		if uavcan start
+		then
+			if param greater UAVCAN_ENABLE 2
+			then
+				set OUTPUT_MODE uavcan_esc
+			fi
+		else
+			tune_control play error
+		fi
+	else
+		if param greater -s UAVCAN_V1_ENABLE 0
+		then
+			uavcan_v1 start
+		fi
+	fi
+
+	#
+	# Check if PX4IO present and update firmware if needed.
+	# Assumption IOFW set to firmware file and IO_PRESENT = no
+	#
+
+	if [ -f $IOFW ]
+	then
+		# Check for the mini using build with px4io fw file
+		# but not a px4IO
+		if ver hwtypecmp V540 V560
+		then
+			param set SYS_USE_IO 0
+		else
+			if px4io checkcrc ${IOFW}
+			then
+				set IO_PRESENT yes
+			else
+				# tune Program PX4IO
+				tune_control play -t 16 # tune 16 = PROG_PX4IO
+
+				if px4io update ${IOFW}
+				then
+					usleep 10000
+					tune_control stop
+					if px4io checkcrc ${IOFW}
+					then
+						tune_control play -t 17 # tune 17 = PROG_PX4IO_OK
+						set IO_PRESENT yes
+					else
+						tune_control play -t 18 # tune 18 = PROG_PX4IO_ERR
+					fi
+				else
+					tune_control stop
+				fi
+			fi
+		fi
+	fi
+
+	#
+	# Set USE_IO flag.
+	#
+	if param compare -s SYS_USE_IO 1
+	then
+		set USE_IO yes
+	fi
+
+	if [ $USE_IO = yes -a $IO_PRESENT = no ]
+	then
+		echo "PX4IO not found"
+		set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
+	fi
+
+	#
+	# RC update (map raw RC input to calibrate manual control)
+	#  start before commander
+	#
+	rc_update start
+	manual_control start
 
 	#
 	# Sensors System (start before Commander so Preflight checks are properly run).
+	# Commander needs to be this early for in-air-restarts.
 	#
 	if param greater SYS_HITL 0
 	then
+		set OUTPUT_MODE hil
 		sensors start -h
-
+		commander start -h
 		# disable GPS
 		param set GPS_1_CONFIG 0
 
 		# start the simulator in hardware if needed
 		if param compare SYS_HITL 2
 		then
-			simulator_sih start
-			sensor_baro_sim start
-			sensor_mag_sim start
-			sensor_gps_sim start
-			sensor_agp_sim start
+			sih start
 		fi
 
 	else
@@ -367,131 +406,26 @@ else
 		fi
 
 		sensors start
-	fi
-
-	#
-	# state estimator selection
-	#
-	if param compare -s EKF2_EN 1
-	then
-		ekf2 start &
-	fi
-
-	if param compare -s LPE_EN 1
-	then
-		local_position_estimator start
-	fi
-
-	if param compare -s ATT_EN 1
-	then
-		attitude_estimator_q start
-	fi
-
-	#
-	# px4io
-	#
-	if px4io supported
-	then
-	# Check if PX4IO present and update firmware if needed.
-		if [ -f $IOFW ]
-		then
-			if ! px4io checkcrc ${IOFW}
-			then
-				# tune Program PX4IO
-				tune_control play -t 16 # tune 16 = PROG_PX4IO
-
-				if px4io update ${IOFW}
-				then
-					usleep 10000
-					tune_control stop
-					if px4io checkcrc ${IOFW}
-					then
-						tune_control play -t 17 # tune 17 = PROG_PX4IO_OK
-					else
-						tune_control play -t 18 # tune 18 = PROG_PX4IO_ERR
-					fi
-				else
-					tune_control stop
-				fi
-			fi
-
-			if ! px4io start
-			then
-				echo "PX4IO start failed"
-				set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
-			fi
-		fi
-	fi
-
-	# Heater driver for temperature regulated IMUs.
-	# The heater needs to start after px4io.
-	if param compare -s SENS_EN_THERMAL 1
-	then
-		heater start
-	fi
-
-
-	#
-	# RC update (map raw RC input to calibrate manual control)
-	#  start before commander
-	#
-	rc_update start
-	manual_control start
-
-	# Start camera trigger, capture and PPS before pwm_out as they might access
-	# pwm pins
-	if param greater -s TRIG_MODE 0
-	then
-		camera_trigger start
-		camera_feedback start
-	fi
-	# PPS capture driver
-	if param greater -s PPS_CAP_ENABLE 0
-	then
-		pps_capture start
-	fi
-	# RPM capture driver
-	if param greater -s RPM_CAP_ENABLE 0
-	then
-		rpm_capture start
-	fi
-	# Camera capture driver
-	if param greater -s CAM_CAP_FBACK 0
-	then
-		if camera_capture start
-		then
-			camera_capture on
-		fi
-	fi
-
-	#
-	# Commander
-	#
-	if param greater SYS_HITL 0
-	then
-		commander start -h
-
-		if ! pwm_out_sim start -m hil
-		then
-			tune_control play error
-		fi
-
-	else
 		commander start
-
-		dshot start
-		pwm_out start
 	fi
 
 	#
 	# Configure vehicle type specific parameters.
-	# Note: rc.vehicle_setup is the entry point for all vehicle type specific setup.
+	# Note: rc.vehicle_setup is the entry point for rc.interface,
+	#       rc.fw_apps, rc.mc_apps, rc.rover_apps, and rc.vtol_apps.
+	#
 	. ${R}etc/init.d/rc.vehicle_setup
 
 	# Pre-takeoff continuous magnetometer calibration
 	if param compare -s MBE_ENABLE 1
 	then
 		mag_bias_estimator start
+	fi
+
+	if param greater -s TRIG_MODE 0
+	then
+		camera_trigger start
+		camera_feedback start
 	fi
 
 	#
@@ -511,17 +445,24 @@ else
 	#
 	. ${R}etc/init.d/rc.serial
 
-	# Must be started after the serial config is read
-	rc_input start $RC_INPUT_ARGS
-
-	# Manages USB interface
-	if param greater -s SYS_USB_AUTO -1
+	if [ $IO_PRESENT = no ]
 	then
-		if ! cdcacm_autostart start
+		# Must be started after the serial config is read
+		rc_input start $RC_INPUT_ARGS
+	fi
+
+	# PPS capture driver (before pwm_out)
+	if param greater -s PPS_CAP_ENABLE 0
+	then
+		pps_capture start
+	fi
+
+	# Camera capture driver (before pwm_out)
+	if param greater -s CAM_CAP_FBACK 0
+	then
+		if camera_capture start
 		then
-			sercon
-			echo "Starting MAVLink on /dev/ttyACM0"
-			mavlink start -d /dev/ttyACM0
+			camera_capture on
 		fi
 	fi
 
@@ -542,12 +483,7 @@ else
 	#
 	# Start a thermal calibration if required.
 	#
-	set RC_THERMAL_CAL ${R}etc/init.d/rc.thermal_cal
-	if [ -f ${RC_THERMAL_CAL} ]
-	then
-		. ${RC_THERMAL_CAL}
-	fi
-	unset RC_THERMAL_CAL
+	. ${R}etc/init.d/rc.thermal_cal
 
 	#
 	# Start gimbal to control mounts such as gimbals, disabled by default.
@@ -579,13 +515,6 @@ else
 		px4flow start -X &
 	fi
 
-	payload_deliverer start
-
-	if param compare -s ICE_EN 1
-	then
-		internal_combustion_engine_control start
-	fi
-
 	#
 	# Optional board supplied extras: rc.board_extras
 	#
@@ -609,12 +538,7 @@ else
 	#
 	# Start the logger.
 	#
-	set RC_LOGGING ${R}etc/init.d/rc.logging
-	if [ -f ${RC_LOGGING} ]
-	then
-		. ${RC_LOGGING}
-	fi
-	unset RC_LOGGING
+	. ${R}etc/init.d/rc.logging
 
 	#
 	# Set additional parameters and env variables for selected AUTOSTART.
@@ -632,27 +556,6 @@ else
 	fi
 	unset BOARD_BOOTLOADER_UPGRADE
 
-	#
-	# Check if UAVCAN is enabled, default to it for ESCs.
-	#
-	if param greater -s UAVCAN_ENABLE 0
-	then
-		# Start core UAVCAN module.
-		if ! uavcan start
-		then
-			tune_control play error
-		fi
-	else
-		if param greater -s CYPHAL_ENABLE 0
-		then
-			cyphal start
-		fi
-	fi
-	if param greater -s ZENOH_ENABLE 0
-	then
-		zenoh start
-	fi
-
 #
 # End of autostart.
 #
@@ -662,20 +565,32 @@ fi
 # Unset all script parameters to free RAM.
 #
 unset R
+unset AUTOCNF
 unset FCONFIG
 unset FEXTRAS
 unset FRC
+unset IO_PRESENT
 unset IOFW
 unset LOGGER_ARGS
 unset LOGGER_BUF
+unset MIXER
+unset MIXER_AUX
+unset MIXER_FILE
+unset OUTPUT_MODE
 unset PARAM_FILE
-unset PARAM_BACKUP_FILE
-unset PARAM_DEFAULTS_VER
+unset PWM_AUX_OUT
+unset PWM_AUX_RATE
+unset PWM_MAIN_RATE
+unset PWM_OUT
+unset PWM_EXTRA_OUT
+unset PWM_EXTRA_RATE
 unset RC_INPUT_ARGS
-unset STORAGE_AVAILABLE
+unset SDCARD_AVAILABLE
 unset SDCARD_EXT_PATH
 unset SDCARD_FORMAT
+unset SDCARD_MIXERS_PATH
 unset STARTUP_TUNE
+unset USE_IO
 unset VEHICLE_TYPE
 
 #
